version: "3.9"

services:
  db:
    platform: linux/x86_64
    image: mysql:8.0.28
    ports:
      - "3306:3306"
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/config:/etc/mysql/conf.d
      - ./db/mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: togather
      MYSQL_USER: togather
      MYSQL_PASSWORD: togather
      TZ: Asia/Seoul